### ISSUE TITLE
Class constructor AllErrorHandler cannot be invoked without 'new'

### ISSUE THREAD

**Issue by morlz** [jkanchelov/all-error-handler#2]
```index.js?7e94:94 Uncaught TypeError: Class constructor AllErrorHandler cannot be invoked without 'new'```

my code is 

```js
const AllErrorHandler = require('all-error-handler')

let errorHandler = new AllErrorHandler((err) => {
	console.log(`Error occured - ${err}`);
})

throw new Error('test')
```

p. s. I will use webpack 4

**Comment by yordan-kanchelov** [comment]
I will check it later tonight. @morlz could you show me your webpack config file?

**Comment by jkanchelov** [comment]
I reproduced the bug. I will try to fix it as soon as possible

**Comment by yordan-kanchelov** [comment]
@morlz it should be all good now
